baseurl: 'https://blogdown-g5.netlify.app/'
title: Anime recommendation
languageCode: en-us
theme: hugo-lithium
googleAnalytics: ''
disqusShortname: ''
ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
permalinks:
  posts: /:year/:month/:title/
menu:
  main:
    - name: About us
      url: /about/
    - name: Check our Github !
      url: https://github.com/ptds2021/project--G5
params:
  foo: bar
  AuthorName: M. Bellier, M. Likoska, V. Rodrigues Telo Ramos, X. Renger, M. Finini
  Subtitle: Project G5
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: A website built through Hugo and blogdown.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
  logo:
    alt: Logo
    height: 60
    url: logo.png
    width: 60
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
